export enum FlightsActions {
  GET_AIRPORTS_LIST = 'GET_AIRPORTS_LIST',
  GET_AIRPORTS_LIST_SUCCESS = 'GET_AIRPORTS_LIST_SUCCESS',
  GET_AIRPORTS_LIST_ERROR = 'GET_AIRPORTS_LIST_ERROR',
  GET_FLIGHT_LIST ='GET_FLIGHT_LIST',
  GET_FLIGHT_LIST_SUCCESS = 'GET_FLIGHT_LIST_SUCCESS',
  GET_FLIGHT_LIST_ERROR = 'GET_FLIGHT_LIST_ERROR' ,
  RESET_FLIGHT_LIST = 'GET_FLIGHT_LIST_ERROR',
  SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS'
};